import type { Component } from "vue";
import {
  SkillCategoryContent,
  SkillCategoryOperations,
  SkillCategoryResearch,
  SkillCategorySourcing,
  SkillCategoryTraffic,
} from "./skill-category-icons";
import { Hand as PermissionHand, ShieldAlert as PermissionAlert, Check as PermissionCheck } from "@lucide/vue";
import {
  ArrowDown,
  ArrowRight,
  ArrowLeftRight,
  BadgeCheck,
  Binoculars,
  BookHeart,
  Bot,
  Boxes,
  ChartColumn,
  CalendarClock,
  ChartNoAxesCombined,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleStop,
  Clock3,
  Copy,
  Ellipsis,
  Download,
  FileChartColumnIncreasing,
  FileCheck2,
  FilePenLine,
  FileSearch,
  FileText,
  FileImage,
  Folder,
  FolderOpen,
  Grid2X2,
  Globe,
  HandCoins,
  Handshake,
  IdCard,
  LibraryBig,
  ListTodo,
  List,
  ListFilter,
  ListTree,
  ListVideo,
  LockKeyhole,
  Megaphone,
  MessagesSquare,
  Image,
  MousePointerClick,
  PackageSearch,
  PackageCheck,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  PenLine,
  Pin,
  PinOff,
  Plug,
  Plus,
  RefreshCw,
  ReceiptText,
  Route,
  ScanSearch,
  Send,
  Settings,
  ShieldCheck,
  ShieldAlert,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Speech,
  SquarePen,
  Store,
  Tags,
  Target,
  Telescope,
  Trash2,
  TriangleAlert,
  TrendingUp,
  Truck,
  UserRound,
  Video,
  Warehouse,
  Waypoints,
  WholeWord,
  Workflow,
  Wrench,
  X,
  ZoomIn,
  ZoomOut,
} from "@lucide/vue";

export const iconRegistry = {
  permissionHand: PermissionHand,
  permissionAlert: PermissionAlert,
  permissionCheck: PermissionCheck,
  assistant: Bot,
  backToBottom: ArrowDown,
  arrowRight: ArrowRight,
  check: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  collapseSidebar: PanelLeftClose,
  copy: Copy,
  dismiss: X,
  download: Download,
  edit: Pencil,
  file: FileText,
  fileImage: FileImage,
  folder: Folder,
  folderOpen: FolderOpen,
  gridView: Grid2X2,
  expandSidebar: PanelLeftOpen,
  knowledge: LibraryBig,
  listView: List,
  image: Image,
  more: Ellipsis,
  message: MessagesSquare,
  newTask: SquarePen,
  pending: Clock3,
  pin: Pin,
  pinOff: PinOff,
  plugin: Plug,
  plus: Plus,
  refresh: RefreshCw,
  scanSearch: ScanSearch,
  scheduledTask: CalendarClock,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  stop: CircleStop,
  store: Store,
  skillContent: Megaphone,
  skillOperations: Wrench,
  skillResearch: ChartNoAxesCombined,
  skillSourcing: PackageSearch,
  skillTraffic: MousePointerClick,
  skillCategoryContent: SkillCategoryContent,
  skillCategoryOperations: SkillCategoryOperations,
  skillCategoryResearch: SkillCategoryResearch,
  skillCategorySourcing: SkillCategorySourcing,
  skillCategoryTraffic: SkillCategoryTraffic,
  // Per-Skill card artwork: one function-specific silhouette per bundled Skill.
  skillSupplierEvaluation: BadgeCheck,
  skillDropshipping: Truck,
  skillSupplierSearch: PackageSearch,
  skillNegotiation: Handshake,
  skillSupplierPerformance: ChartColumn,
  skillMarketIntelligence: ArrowLeftRight,
  skillCompetitorAnalysis: Binoculars,
  skillCrossBorderSelection: Globe,
  skillMarketDataAnalysis: FileChartColumnIncreasing,
  skillDemandTrends: TrendingUp,
  skillProductAttributes: SlidersHorizontal,
  skillProductRanking: ListFilter,
  skillReviewAnalysis: Speech,
  skillScenarioDiscovery: Telescope,
  skillContentBreakdown: ListTree,
  skillContentStrategy: Route,
  skillCopywriting: PenLine,
  skillMarketingContext: IdCard,
  skillSocialContent: Waypoints,
  skillBrandMood: Sparkles,
  skillLifestyleContent: BookHeart,
  skillListingReview: FileCheck2,
  skillPpcCampaign: Target,
  skillTrendingKeywords: WholeWord,
  skillProductOptimization: PackageCheck,
  skillEcommerceSeo: ShoppingBag,
  skillMarketplaceTags: Tags,
  skillProductDescription: FilePenLine,
  skillKeywordResearch: FileSearch,
  skillVideoAdvertising: ListVideo,
  skillBrandProtection: ShieldCheck,
  skillInstallmentPayments: HandCoins,
  skillPrivacyCompliance: LockKeyhole,
  skillInvoicing: ReceiptText,
  skillInventorySync: Boxes,
  skillPaymentRisk: ShieldAlert,
  skillShopSetup: Store,
  skillWarehouseFulfillment: Warehouse,
  taskHistory: ListTodo,
  trash: Trash2,
  user: UserRound,
  video: Video,
  warning: TriangleAlert,
  workspace: Workflow,
  workflow: Workflow,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
} as const satisfies Record<string, Component>;

export type YjIconName = keyof typeof iconRegistry;

export function isYjIconName(value: string): value is YjIconName {
  return Object.prototype.hasOwnProperty.call(iconRegistry, value);
}
