import type { Component } from "vue";
import {
  ArrowDown,
  Bot,
  CalendarClock,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleStop,
  Clock3,
  Ellipsis,
  Folder,
  FolderOpen,
  LayoutDashboard,
  LibraryBig,
  ListTodo,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Pin,
  PinOff,
  Plug,
  RefreshCw,
  Send,
  Settings,
  ShieldCheck,
  SquarePen,
  Store,
  Trash2,
  TriangleAlert,
  UserRound,
  X,
} from "@lucide/vue";

export const iconRegistry = {
  assistant: Bot,
  backToBottom: ArrowDown,
  check: CheckCircle2,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  collapseSidebar: PanelLeftClose,
  dismiss: X,
  edit: Pencil,
  folder: Folder,
  folderOpen: FolderOpen,
  expandSidebar: PanelLeftOpen,
  knowledge: LibraryBig,
  more: Ellipsis,
  newTask: SquarePen,
  pending: Clock3,
  pin: Pin,
  pinOff: PinOff,
  plugin: Plug,
  refresh: RefreshCw,
  scheduledTask: CalendarClock,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  stop: CircleStop,
  store: Store,
  taskHistory: ListTodo,
  trash: Trash2,
  user: UserRound,
  warning: TriangleAlert,
  workspace: LayoutDashboard,
} as const satisfies Record<string, Component>;

export type YjIconName = keyof typeof iconRegistry;
