/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/workflow-local/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetWorkflowStatus
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        get: operations["GetWorkflowStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-local/principal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * EnsureLocalPrincipal
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        post: operations["EnsureLocalPrincipal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListWorkflows
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        get: operations["ListWorkflows"];
        put?: never;
        /**
         * CreateWorkflow
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        post: operations["CreateWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ReadWorkflow
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        get: operations["ReadWorkflow"];
        /**
         * SaveWorkflow
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        put: operations["SaveWorkflow"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{workflow_id}/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GetEditorBootstrap
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        get: operations["GetEditorBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{workflow_id}/test-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * TestWorkflow
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        post: operations["TestWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{workflow_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * PublishWorkflow
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        post: operations["PublishWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{workflow_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ListWorkflowRuns
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        get: operations["ListWorkflowRuns"];
        put?: never;
        /**
         * RunWorkflow
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        post: operations["RunWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflows/{workflow_id}/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ReadWorkflowRun
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        get: operations["ReadWorkflowRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-local/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ReadWorkflowOperation
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        get: operations["ReadWorkflowOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-local/editor-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OpenEditorSession
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        post: operations["OpenEditorSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workflow-local/editor-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * CloseEditorSession
         * @description Exact local/profile gate and authenticated fixed scope; identifiers alone do not authorize access.
         */
        delete: operations["CloseEditorSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Identifier: string;
        OperationId: string;
        Version: string;
        RunEpoch: components["schemas"]["OperationId"];
        /** @enum {string} */
        ErrorCode: "profile_disabled" | "service_unavailable" | "unauthorized" | "session_expired" | "resource_not_found" | "revision_conflict" | "operation_conflict" | "invalid_draft" | "input_too_large" | "run_busy" | "operation_unknown" | "protocol_mismatch" | "invalid_request" | "storage_unavailable" | "internal_error";
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            operation_id?: components["schemas"]["OperationId"];
        };
        Limits: {
            /**
             * Format: int64
             * @enum {integer}
             */
            input_bytes: 4096;
            /**
             * Format: int64
             * @enum {integer}
             */
            prefix_bytes: 1024;
            /**
             * Format: int64
             * @enum {integer}
             */
            output_bytes: 5120;
            /**
             * Format: int64
             * @enum {integer}
             */
            canvas_bytes: 262144;
            /**
             * Format: int64
             * @enum {integer}
             */
            message_bytes: 524288;
            /**
             * Format: int64
             * @enum {integer}
             */
            max_active_runs: 1;
            /**
             * Format: int64
             * @enum {integer}
             */
            execution_budget_seconds: 30;
            /**
             * Format: int64
             * @enum {integer}
             */
            editor_ttl_seconds: 300;
        };
        ServiceStatus: {
            /**
             * Format: int64
             * @enum {integer}
             */
            protocol_version: 1;
            run_epoch: components["schemas"]["RunEpoch"];
            ready: boolean;
            /** @enum {string} */
            state: "ready" | "unavailable" | "disabled";
            limits: components["schemas"]["Limits"];
        };
        Principal: {
            owner_id: components["schemas"]["Identifier"];
            tenant_id: components["schemas"]["Identifier"];
            user_id: components["schemas"]["Identifier"];
            space_id: components["schemas"]["Identifier"];
        };
        /** @description Coze-owned graph and revision. Canvas is native JSON text; safe incomplete drafts may be saved. IDs are opaque strings, including decimal Coze IDs, never JS numbers. */
        Workflow: {
            workflow_id: components["schemas"]["Identifier"];
            name: string;
            revision: components["schemas"]["Identifier"];
            canvas: string;
            runnable: boolean;
            published_version?: components["schemas"]["Version"];
            /** Format: int64 */
            updated_at_ms: number;
        };
        WorkflowList: {
            items: components["schemas"]["WorkflowSummary"][];
            next_cursor?: string;
        };
        ListRequest: {
            cursor?: string;
            /**
             * Format: int64
             * @default 20
             */
            limit?: number;
        };
        CreateInput: {
            name: string;
        };
        CreateRequest: {
            name: string;
            operation_id: components["schemas"]["OperationId"];
        };
        TextInput: {
            input: string;
        };
        SaveRequest: {
            operation_id: components["schemas"]["OperationId"];
            expected_revision: components["schemas"]["Identifier"];
            name: string;
            canvas: string;
        };
        TestRequest: {
            operation_id: components["schemas"]["OperationId"];
            expected_revision: components["schemas"]["Identifier"];
            input: components["schemas"]["TextInput"];
        };
        PublishRequest: {
            operation_id: components["schemas"]["OperationId"];
            expected_revision: components["schemas"]["Identifier"];
            successful_test_run_id: components["schemas"]["Identifier"];
        };
        RunRequest: {
            operation_id: components["schemas"]["OperationId"];
            version: components["schemas"]["Version"];
            input: components["schemas"]["TextInput"];
        };
        RunInput: {
            workflow_id: components["schemas"]["Identifier"];
            version: components["schemas"]["Version"];
            input: components["schemas"]["TextInput"];
        };
        /** @enum {string} */
        RunMode: "debug" | "release";
        NodeResult: {
            node_id: components["schemas"]["Identifier"];
            state: string;
            output?: string;
            error?: components["schemas"]["ErrorResponse"];
        };
        Run: {
            run_id: components["schemas"]["Identifier"];
            workflow_id: components["schemas"]["Identifier"];
            operation_id: components["schemas"]["OperationId"];
            mode: components["schemas"]["RunMode"];
            revision?: components["schemas"]["Identifier"];
            version?: components["schemas"]["Version"];
            /** @description Actual engine status; new values stay visible and never imply success. */
            state: string;
            terminal: boolean;
            input?: components["schemas"]["TextInput"];
            output?: string;
            nodes?: components["schemas"]["NodeResult"][];
            /** Format: int64 */
            started_at_ms: number;
            /** Format: int64 */
            finished_at_ms?: number;
            error?: components["schemas"]["ErrorResponse"];
        };
        RunList: {
            items: components["schemas"]["RunSummary"][];
            next_cursor?: string;
        };
        /** @enum {string} */
        OperationKind: "create" | "save" | "test" | "publish" | "run";
        /** @enum {string} */
        OperationPhase: "recorded" | "completed" | "unknown" | "rejected";
        /** @description Dispatch receipt, not engine status. completed identifies committed resource/execution registration, not successful workflow execution. */
        OperationReceipt: {
            operation_id: components["schemas"]["OperationId"];
            kind: components["schemas"]["OperationKind"];
            phase: components["schemas"]["OperationPhase"];
            workflow_id?: components["schemas"]["Identifier"];
            revision?: components["schemas"]["Identifier"];
            /** @description Version registered by this operation: the newly committed version for publish, or the selected published version for a release run. Omitted for create, save, and debug test operations; never copies Workflow.published_version as ambient resource metadata. */
            version?: components["schemas"]["Version"];
            run_id?: components["schemas"]["Identifier"];
            error?: components["schemas"]["ErrorResponse"];
        };
        EditorOpenRequest: {
            workflow_id: components["schemas"]["Identifier"];
        };
        EditorSessionSecret: {
            session_id: components["schemas"]["Identifier"];
            workflow_id: components["schemas"]["Identifier"];
            /** @description Native/API only. Never serialize this response to renderer, URL, log or MessageChannel. */
            secret: string;
            run_epoch: components["schemas"]["RunEpoch"];
            /** Format: int64 */
            expires_at_ms: number;
        };
        EditorOpenedView: {
            bridge_id: components["schemas"]["Identifier"];
            workflow: components["schemas"]["Workflow"];
            /** Format: int64 */
            generation: number;
            /** Format: int64 */
            expires_at_ms: number;
            /**
             * Format: int64
             * @enum {integer}
             */
            protocol_version: 1;
        };
        Bootstrap: {
            workflow: components["schemas"]["Workflow"];
            principal: components["schemas"]["Principal"];
            node_types: (1 | 15 | 2)[];
            limits: components["schemas"]["Limits"];
        };
        /** @enum {string} */
        EditorOperation: "bootstrap" | "read_draft" | "save_draft" | "test_draft" | "publish_internal" | "read_run" | "read_operation";
        /** @description Native generates write operation IDs. operation_id input is only a read_operation lookup. No actor, secret, URL, headers or arbitrary command. */
        EditorExchangeInput: {
            bridge_id: components["schemas"]["Identifier"];
            /** Format: int64 */
            generation: number;
            /**
             * Format: int64
             * @enum {integer}
             */
            protocol_version: 1;
            request_id: components["schemas"]["Identifier"];
            operation: components["schemas"]["EditorOperation"];
            expected_revision?: components["schemas"]["Identifier"];
            name?: string;
            canvas?: string;
            input?: components["schemas"]["TextInput"];
            successful_test_run_id?: components["schemas"]["Identifier"];
            run_id?: components["schemas"]["Identifier"];
            operation_id?: components["schemas"]["OperationId"];
        };
        EditorExchangeResult: {
            request_id: components["schemas"]["Identifier"];
            operation_id?: components["schemas"]["OperationId"];
            bootstrap?: components["schemas"]["Bootstrap"];
            workflow?: components["schemas"]["Workflow"];
            run?: components["schemas"]["Run"];
            receipt?: components["schemas"]["OperationReceipt"];
        };
        EditorCloseInput: {
            bridge_id: components["schemas"]["Identifier"];
        };
        /** @enum {string} */
        RunQueryKind: "run" | "history" | "operation";
        RunQueryInput: {
            kind: components["schemas"]["RunQueryKind"];
            workflow_id?: components["schemas"]["Identifier"];
            run_id?: components["schemas"]["Identifier"];
            operation_id?: components["schemas"]["OperationId"];
            cursor?: string;
            /**
             * Format: int64
             * @default 20
             */
            limit?: number;
        };
        RunQueryResult: {
            run?: components["schemas"]["Run"];
            history?: components["schemas"]["RunList"];
            receipt?: components["schemas"]["OperationReceipt"];
        };
        CloseResult: {
            closed: boolean;
        };
        /** @description Bounded list summary; read the detail endpoint for full content. */
        WorkflowSummary: {
            workflow_id: components["schemas"]["Identifier"];
            name: string;
            revision: components["schemas"]["Identifier"];
            runnable: boolean;
            published_version?: components["schemas"]["Version"];
            /** Format: int64 */
            updated_at_ms: number;
        };
        /** @description Bounded list summary; read the detail endpoint for full content. */
        RunSummary: {
            run_id: components["schemas"]["Identifier"];
            workflow_id: components["schemas"]["Identifier"];
            operation_id: components["schemas"]["OperationId"];
            mode: components["schemas"]["RunMode"];
            revision?: components["schemas"]["Identifier"];
            version?: components["schemas"]["Version"];
            /** @description Actual engine status; new values stay visible and never imply success. */
            state: string;
            terminal: boolean;
            /** Format: int64 */
            started_at_ms: number;
            /** Format: int64 */
            finished_at_ms?: number;
            error?: components["schemas"]["ErrorResponse"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetWorkflowStatus: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    EnsureLocalPrincipal: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Principal"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListWorkflows: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowList"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CreateWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRequest"];
            };
        };
        responses: {
            /** @description Resource or dispatch result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ReadWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path: {
                workflow_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    SaveWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
                /** @description Native-only E. Coze private adapter validates K_AC instead; this API session header is never forwarded to Coze. */
                "X-Yijie-Editor-Session": string;
            };
            path: {
                workflow_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRequest"];
            };
        };
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetEditorBootstrap: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
                /** @description Native-only E. Coze private adapter validates K_AC instead; this API session header is never forwarded to Coze. */
                "X-Yijie-Editor-Session": string;
            };
            path: {
                workflow_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Bootstrap"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    TestWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
                /** @description Native-only E. Coze private adapter validates K_AC instead; this API session header is never forwarded to Coze. */
                "X-Yijie-Editor-Session": string;
            };
            path: {
                workflow_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestRequest"];
            };
        };
        responses: {
            /** @description Resource or dispatch result. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    PublishWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
                /** @description Native-only E. Coze private adapter validates K_AC instead; this API session header is never forwarded to Coze. */
                "X-Yijie-Editor-Session": string;
            };
            path: {
                workflow_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workflow"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ListWorkflowRuns: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path: {
                workflow_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunList"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    RunWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path: {
                workflow_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Resource or dispatch result. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ReadWorkflowRun: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path: {
                workflow_id: components["schemas"]["Identifier"];
                run_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ReadWorkflowOperation: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path: {
                operation_id: components["schemas"]["OperationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationReceipt"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    OpenEditorSession: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditorOpenRequest"];
            };
        };
        responses: {
            /** @description Resource or dispatch result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorSessionSecret"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CloseEditorSession: {
        parameters: {
            query?: never;
            header: {
                "X-Yijie-Run-Epoch": components["schemas"]["RunEpoch"];
            };
            path: {
                session_id: components["schemas"]["Identifier"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource or dispatch result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloseResult"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Safe typed error. Retry must preserve operation semantics. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
