// Generated by scripts/generate-native-conversation.mjs. Do not edit.
#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub kind: String,
    #[serde(rename = "clientId", default, skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    #[serde(rename = "text", default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    #[serde(rename = "phase", default, skip_serializing_if = "Option::is_none")]
    pub phase: Option<String>,
    #[serde(rename = "summary", default, skip_serializing_if = "Option::is_none")]
    pub summary: Option<Vec<String>>,
    #[serde(rename = "content", default, skip_serializing_if = "Option::is_none")]
    pub content: Option<Vec<String>>,
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "exitCode", default, skip_serializing_if = "Option::is_none")]
    pub exit_code: Option<i64>,
    #[serde(
        rename = "durationMs",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub duration_ms: Option<i64>,
    #[serde(
        rename = "argumentsSummary",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub arguments_summary: Option<String>,
    #[serde(
        rename = "resultSummary",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub result_summary: Option<String>,
    #[serde(rename = "availability")]
    pub availability: String,
    #[serde(
        rename = "commandLabel",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub command_label: Option<String>,
    #[serde(rename = "cwdLabel", default, skip_serializing_if = "Option::is_none")]
    pub cwd_label: Option<String>,
    #[serde(
        rename = "outputText",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub output_text: Option<String>,
    #[serde(rename = "toolLabel", default, skip_serializing_if = "Option::is_none")]
    pub tool_label: Option<String>,
}
impl std::fmt::Debug for NativeItem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeItem([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeTurn {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "status")]
    pub status: Option<String>,
    #[serde(rename = "errorCode", default, skip_serializing_if = "Option::is_none")]
    pub error_code: Option<String>,
    #[serde(rename = "items")]
    pub items: Vec<NativeItem>,
    #[serde(rename = "itemsComplete")]
    pub items_complete: bool,
    #[serde(rename = "error", default, skip_serializing_if = "Option::is_none")]
    pub error: Option<NativeError>,
}
impl std::fmt::Debug for NativeTurn {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeTurn([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativePlanStep {
    #[serde(rename = "step")]
    pub step: String,
    #[serde(rename = "status")]
    pub status: String,
}
impl std::fmt::Debug for NativePlanStep {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativePlanStep([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeNotification {
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "method")]
    pub method: String,
    #[serde(rename = "threadId")]
    pub thread_id: String,
    #[serde(rename = "turnId", default, skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
    #[serde(rename = "itemId", default, skip_serializing_if = "Option::is_none")]
    pub item_id: Option<String>,
    #[serde(rename = "item", default, skip_serializing_if = "Option::is_none")]
    pub item: Option<NativeItem>,
    #[serde(rename = "turn", default, skip_serializing_if = "Option::is_none")]
    pub turn: Option<NativeTurn>,
    #[serde(rename = "delta", default, skip_serializing_if = "Option::is_none")]
    pub delta: Option<String>,
    #[serde(rename = "index", default, skip_serializing_if = "Option::is_none")]
    pub index: Option<i64>,
    #[serde(rename = "plan", default, skip_serializing_if = "Option::is_none")]
    pub plan: Option<Vec<NativePlanStep>>,
    #[serde(
        rename = "explanation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub explanation: Option<String>,
    #[serde(rename = "code", default, skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "availability")]
    pub availability: String,
}
impl std::fmt::Debug for NativeNotification {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeNotification([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeThreadSnapshot {
    #[serde(rename = "schema_version")]
    pub schema_version: i64,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "thread_id")]
    pub thread_id: String,
    #[serde(rename = "turns")]
    pub turns: Vec<NativeTurn>,
    #[serde(rename = "availability")]
    pub availability: String,
}
impl std::fmt::Debug for NativeThreadSnapshot {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeThreadSnapshot([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeEventPayload {
    #[serde(rename = "native")]
    pub native: NativeNotification,
}
impl std::fmt::Debug for NativeEventPayload {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeEventPayload([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeEvent {
    #[serde(rename = "schema_version")]
    pub schema_version: i64,
    #[serde(rename = "event_id")]
    pub event_id: String,
    #[serde(rename = "stream_id")]
    pub stream_id: String,
    #[serde(rename = "sequence")]
    pub sequence: i64,
    #[serde(rename = "occurred_at")]
    pub occurred_at: String,
    #[serde(rename = "task_id")]
    pub task_id: String,
    #[serde(rename = "agent_session_id")]
    pub agent_session_id: String,
    #[serde(rename = "codex_thread_id")]
    pub codex_thread_id: String,
    #[serde(rename = "turn_id", default, skip_serializing_if = "Option::is_none")]
    pub turn_id: Option<String>,
    #[serde(rename = "item_id", default, skip_serializing_if = "Option::is_none")]
    pub item_id: Option<String>,
    #[serde(rename = "event_type")]
    pub event_type: String,
    #[serde(rename = "terminal")]
    pub terminal: bool,
    #[serde(rename = "payload")]
    pub payload: NativeEventPayload,
}
impl std::fmt::Debug for NativeEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeEvent([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeError {
    #[serde(rename = "availability")]
    pub availability: String,
    #[serde(
        rename = "messageText",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub message_text: Option<String>,
    #[serde(
        rename = "codexErrorInfo",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub codex_error_info: Option<String>,
}
impl std::fmt::Debug for NativeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeError([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeDisplayItem {
    #[serde(rename = "item")]
    pub item: NativeItem,
    #[serde(rename = "lastMethod")]
    pub last_method: String,
    #[serde(rename = "ordinal")]
    pub ordinal: i64,
}
impl std::fmt::Debug for NativeDisplayItem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeDisplayItem([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeViewCursor {
    #[serde(rename = "streamId")]
    pub stream_id: String,
    #[serde(rename = "sequence")]
    pub sequence: String,
    #[serde(rename = "eventId")]
    pub event_id: String,
}
impl std::fmt::Debug for NativeViewCursor {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeViewCursor([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeConversationView {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "turnId")]
    pub turn_id: String,
    #[serde(rename = "runtimeThreadId")]
    pub runtime_thread_id: String,
    #[serde(rename = "runtimeTurnId")]
    pub runtime_turn_id: String,
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "revision")]
    pub revision: String,
    #[serde(rename = "availability")]
    pub availability: String,
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    #[serde(rename = "terminalObserved")]
    pub terminal_observed: bool,
    #[serde(rename = "items")]
    pub items: Vec<NativeDisplayItem>,
    #[serde(rename = "plan", default, skip_serializing_if = "Option::is_none")]
    pub plan: Option<Vec<NativePlanStep>>,
    #[serde(
        rename = "explanation",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub explanation: Option<String>,
    #[serde(
        rename = "diagnostic",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub diagnostic: Option<String>,
    #[serde(rename = "cursor", default, skip_serializing_if = "Option::is_none")]
    pub cursor: Option<NativeViewCursor>,
    #[serde(
        rename = "terminalErrorCode",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub terminal_error_code: Option<String>,
    #[serde(rename = "ordinal", default, skip_serializing_if = "Option::is_none")]
    pub ordinal: Option<i64>,
    #[serde(
        rename = "statusSource",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub status_source: Option<String>,
}
impl std::fmt::Debug for NativeConversationView {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeConversationView([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeConversationViewEvent {
    #[serde(rename = "schemaVersion")]
    pub schema_version: i64,
    #[serde(rename = "contextId")]
    pub context_id: String,
    #[serde(rename = "subscriptionId")]
    pub subscription_id: String,
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "view")]
    pub view: NativeConversationView,
}
impl std::fmt::Debug for NativeConversationViewEvent {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeConversationViewEvent([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeConversationHistory {
    #[serde(rename = "views")]
    pub views: Vec<NativeConversationView>,
    #[serde(rename = "historyAvailability")]
    pub history_availability: String,
    #[serde(rename = "submissions")]
    pub submissions: Vec<LocalSubmissionView>,
    #[serde(rename = "remainingTurnIds")]
    pub remaining_turn_ids: Vec<String>,
}
impl std::fmt::Debug for NativeConversationHistory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeConversationHistory([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NativeHistoryRequest {
    #[serde(rename = "sessionId")]
    pub session_id: String,
    #[serde(rename = "turnIds")]
    pub turn_ids: Vec<String>,
}
impl std::fmt::Debug for NativeHistoryRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("NativeHistoryRequest([REDACTED])")
    }
}

#[derive(Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LocalSubmissionView {
    #[serde(rename = "turnId")]
    pub turn_id: String,
    #[serde(rename = "operationId")]
    pub operation_id: String,
    #[serde(rename = "status")]
    pub status: String,
}
impl std::fmt::Debug for LocalSubmissionView {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("LocalSubmissionView([REDACTED])")
    }
}
