// @vitest-environment happy-dom
import { mount, flushPromises } from "@vue/test-utils";
import { defineComponent, ref } from "vue";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { modelDefinitions } from "../domain/chat-models.generated";
import { useChatModels } from "./useChatModels";
const client=vi.hoisted(()=>({catalog:vi.fn(),state:vi.fn(),select:vi.fn()}));
vi.mock("../api/chat-model-client",()=>({chatModelsEnabled:true,chatModelClient:client}));
const wrappers:ReturnType<typeof mount>[]=[];
function setup(id:string|null=null){const session=ref(id),busy=ref(false);let models!:ReturnType<typeof useChatModels>;wrappers.push(mount(defineComponent({setup(){models=useChatModels(()=>"scope",()=>session.value,()=>busy.value);return()=>null;}})));return{models,session,busy};}
beforeEach(()=>{vi.resetAllMocks();client.catalog.mockResolvedValue({schema_version:1,default_profile:"kimi-k3-max-v1",models:modelDefinitions.map(profile=>({profile,available:true,reason:"ready"}))});client.state.mockResolvedValue({profileId:"minimax-m3-high-v1",revision:0,state:"ready"});});
afterEach(()=>wrappers.splice(0).forEach(w=>w.unmount()));
it("defaults new drafts to Kimi and binds existing chats to their own selection",async()=>{const{models,session}=setup();await flushPromises();expect(models.intent.value).toEqual({profileId:"kimi-k3-max-v1",expectedRevision:0});session.value="legacy";await flushPromises();expect(models.profile.value).toBe("minimax-m3-high-v1");expect(client.select).not.toHaveBeenCalled();});
it("keeps a failed read blocked and never dispatches selection while busy",async()=>{const{models,busy}=setup("existing");await flushPromises();busy.value=true;await models.select("kimi-k3-max-v1");expect(client.select).not.toHaveBeenCalled();client.state.mockRejectedValue(new Error("unavailable"));await models.refresh();expect(models.ready.value).toBe(false);expect(models.intent.value).toBeUndefined();});
it("restores the original unresolved operation after reopening",async()=>{const operationId=crypto.randomUUID();client.state.mockResolvedValue({profileId:"minimax-m3-high-v1",revision:0,state:"unknown",pending:{profileId:"kimi-k3-max-v1",expectedRevision:0,operationId}});const{models}=setup("existing");await flushPromises();expect(models.ready.value).toBe(false);client.select.mockResolvedValue({profileId:"kimi-k3-max-v1",revision:1,state:"ready"});await models.retry();expect(client.select).toHaveBeenCalledExactlyOnceWith("scope","existing",{profileId:"kimi-k3-max-v1",expectedRevision:0},operationId);expect(models.ready.value).toBe(true);});
it("discards a late switch receipt after navigating to another chat",async()=>{let resolve!:(v:unknown)=>void;client.select.mockReturnValue(new Promise(r=>{resolve=r;}));const{models,session}=setup("a");await flushPromises();const pending=models.select("kimi-k3-max-v1");session.value="b";await flushPromises();resolve({profileId:"kimi-k3-max-v1",revision:1,state:"ready"});await pending;expect(models.profile.value).toBe("minimax-m3-high-v1");});
it("keeps an unconfigured Kimi default blocked until an explicit available selection",async()=>{client.catalog.mockResolvedValue({schema_version:1,default_profile:"kimi-k3-max-v1",models:modelDefinitions.map(profile=>({profile,available:profile.provider!=="kimi",reason:profile.provider==="kimi"?"not_configured":"ready"}))});const{models}=setup();await flushPromises();expect(models.profile.value).toBe("kimi-k3-max-v1");expect(models.ready.value).toBe(false);expect(models.intent.value).toBeUndefined();await models.select("minimax-m3-high-v1");expect(models.ready.value).toBe(true);expect(client.select).not.toHaveBeenCalled();});
it("clears the pending operation after a successful reconciliation read",async()=>{const{models}=setup("existing");await flushPromises();client.select.mockRejectedValueOnce(new Error("unavailable"));await models.select("kimi-k3-max-v1");expect(models.ready.value).toBe(false);client.state.mockResolvedValue({profileId:"kimi-k3-max-v1",revision:1,state:"ready"});await models.refresh();client.select.mockResolvedValue({profileId:"minimax-m3-high-v1",revision:2,state:"ready"});await models.select("minimax-m3-high-v1");expect(client.select).toHaveBeenCalledTimes(2);expect(models.profile.value).toBe("minimax-m3-high-v1");expect(models.ready.value).toBe(true);});
